version: '3'
services:
  mysql:
    restart: always
    image: mysql
    container_name: mysql-turbomac
    volumes:
      - ./data/mysql/conf:/etc/mysql/conf.d
      - ./data/mysql/logs:/logs
      - ./data/mysql/data:/var/lib/mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      # 宿主机：容器
      - 3306:3306
